# cado-nfs.py zsh completion -- GENERATED by scripts/build-completions.py
# from cadofactor/toplevel.py. Do NOT hand-edit; regenerate instead:
#   PYTHONPATH=scripts cado-nfs.venv/bin/python3 scripts/build-completions.py

#compdef cado-nfs.py

_cado_nfs_py() {
  _arguments -s \
    '--autotune[Calibrate only the SAFE scheduling knobs to this host -- local client/]' \
    '--checkpoint-interval=[Linear-algebra (Block Wiedemann) checkpoint cadence: krylov saves a re]:value:' \
    '--cl[Run class group computation]' \
    '--client-threads=[Number of threads for sieving and polynomial selection jobs.]:value:' \
    '--dlp[Run discrete logarithm computation]' \
    '--dlp-no-keep[Disable the feature that CADO_DEBUG is set by default in dlp mode]' \
    '--doctor[Run a side-effect-free preflight: check the build, CPU/SIMD, GPU, free]' \
    '--doctor-json[Like --doctor, but emit the report as JSON.]' \
    '--ell=[Aliases (and conflicts with) ell in parameter files]:value:' \
    '--fact[Run factorization computation]' \
    '--filelog=[Log file logging level, e.g.,  INFO/COMMAND/DEBUG]:value:' \
    '--galois-detect=[Analyse a CADO .poly file for a field automorphism and print the match]:value:' \
    '--gfpext=[Degree of the finite field extension (DLP only)]:value:' \
    '--gpu-b1=[GPU ECM stage-1 bound for --gpu-prefactor]:value:' \
    '--gpu-b2=[GPU ECM stage-2 bound (0 = 100*B1)]:value:' \
    '--gpu-curves=[GPU ECM curves for --gpu-prefactor]:value:' \
    '--gpu-polyselect[EXPERIMENTAL: offload polynomial-selection collision search to the GPU]' \
    '--gpu-prefactor[Before NFS, strip small/medium factors with GPU ECM (misc/gpu_prefacto]' \
    '--host-speed=[Per-core speed of this host relative to the benchmark reference (1.0 =]:value:' \
    '--json-status=[Write a machine-readable run-status snapshot (phase, percent, ETA, wor]:file:_files' \
    '--mysql[Use a mysql db for tracking workunits etc]' \
    '--mysql-password=[Use a mysql db for tracking workunits etc]:value:' \
    '--mysql-user=[Use a mysql db for tracking workunits etc]:value:' \
    '--nfs[Use NFS and its variants]' \
    '--no-colors[Turn off colored output]' \
    '--parameters=[A file with the parameters to use]:file:_files' \
    '--plan[Estimate feasibility, a wall-time envelope, the rough per-phase split,]' \
    '--plan-json[Like --plan, but emit the plan as JSON and exit.]' \
    '--progress[Show a compact single-line progress indicator (phase, percent, ETA) on]' \
    '--qs[Use QS and its variants]' \
    '--screenlog=[Screen logging level, e.g., INFO/COMMAND/DEBUG]:value:' \
    '--server[Run a bare server, do not start any clients]' \
    '--server-threads=[Overrides tasks.threads. NCORES may be "all", which then is the number]:threads:(all 1 2 4 8 16)' \
    '--slaves=[Aliases (and conflicts with) slaves.nrclients]:value:' \
    '--suggest-params[Resolve the default parameter file for N (interpolating between the ne]' \
    '--suggest-pbs-config[Like --suggest-slurm-config, but emit a PBS (qsub) submission script.]' \
    '--suggest-slurm-config[Print a ready-to-edit Slurm (sbatch) submission script sized to N (wal]' \
    '--verboseparam[Enable very verbose parameter parsing]' \
    '--wdir=[Aliases (and conflicts with) tasks.workdir. WORKDIR is created if it d]:file:_files' \
    '--workdir=[Aliases (and conflicts with) tasks.workdir. WORKDIR is created if it d]:file:_files' \
    '-cl[Run class group computation]' \
    '-dlp[Run discrete logarithm computation]' \
    '-dlp-no-keep[Disable the feature that CADO_DEBUG is set by default in dlp mode]' \
    '-ell=[Aliases (and conflicts with) ell in parameter files]:value:' \
    '-fact[Run factorization computation]' \
    '-gfpext=[Degree of the finite field extension (DLP only)]:value:' \
    '-mysql[Use a mysql db for tracking workunits etc]' \
    '-mysql-password=[Use a mysql db for tracking workunits etc]:value:' \
    '-mysql-user=[Use a mysql db for tracking workunits etc]:value:' \
    '-nfs[Use NFS and its variants]' \
    '-p=[A file with the parameters to use]:file:_files' \
    '-qs[Use QS and its variants]' \
    '-s=[Aliases (and conflicts with) slaves.nrclients]:value:' \
    '-t=[Overrides tasks.threads. NCORES may be "all", which then is the number]:threads:(all 1 2 4 8 16)' \
    '-w=[Aliases (and conflicts with) tasks.workdir. WORKDIR is created if it d]:file:_files' \
    '*:option (N or key=value):_files'
}
_cado_nfs_py "$@"
