# cado-nfs.py bash completion -- GENERATED by scripts/build-completions.py
# from cadofactor/toplevel.py. Do NOT hand-edit; regenerate instead:
#   PYTHONPATH=scripts cado-nfs.venv/bin/python3 scripts/build-completions.py

_cado_nfs_py()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="--autotune --calibrate --checkpoint-interval --cl --client-threads --compare-runs --dlp --dlp-no-keep --doctor --doctor-json --ell --fact --filelog --galois-detect --gfpext --gpu-b1 --gpu-b2 --gpu-curves --gpu-polyselect --gpu-prefactor --help --host-speed --json-log --json-status --list-runs --mysql --mysql-password --mysql-user --nfs --no-colors --notify --parameters --plan --plan-json --progress --qs --screenlog --server --server-threads --slaves --suggest-params --suggest-pbs-config --suggest-slurm-config --verboseparam --wdir --wizard --workdir -cl -dlp -dlp-no-keep -ell -fact -gfpext -h -mysql -mysql-password -mysql-user -nfs -p -qs -s -t -w"

    case "$prev" in
        --galois-detect|--json-log|--json-status|--parameters|--wdir|--workdir|-p|-w)
            COMPREPLY=( $(compgen -f -- "$cur") )
            return 0 ;;
        --server-threads|-t)
            COMPREPLY=( $(compgen -W "all 1 2 4 8 16" -- "$cur") )
            return 0 ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return 0
    fi
    # Otherwise the user is typing N or a key=value option; offer files too.
    COMPREPLY=( $(compgen -W "--autotune --calibrate --checkpoint-interval --cl --client-threads --compare-runs --dlp --dlp-no-keep --doctor --doctor-json --ell --fact --filelog --galois-detect --gfpext --gpu-b1 --gpu-b2 --gpu-curves --gpu-polyselect --gpu-prefactor --help --host-speed --json-log --json-status --list-runs --mysql --mysql-password --mysql-user --nfs --no-colors --notify --parameters --plan --plan-json --progress --qs --screenlog --server --server-threads --slaves --suggest-params --suggest-pbs-config --suggest-slurm-config --verboseparam --wdir --wizard --workdir" -f -- "$cur") )
    return 0
}
complete -F _cado_nfs_py cado-nfs.py
complete -F _cado_nfs_py ./cado-nfs.py
