#!/usr/bin/env python3
"""Generate shell completions for cado-nfs.py from its argparse spec.

This introspects the *single source of truth* — the argparse parser built by
``cadofactor.toplevel.Cado_NFS_toplevel.default_parser()`` — and emits bash, zsh
and fish completion scripts into ``misc/completions/``. The generated files are
committed so end users do not need to run this; regenerate (and commit the diff)
whenever a flag is added/removed in ``toplevel.py``:

    PYTHONPATH=scripts cado-nfs.venv/bin/python3 scripts/build-completions.py

It is fork-local tooling (3.3.0-modern, Roadmap E6); see docs/usability-v330.md.

Design notes
------------
* Options that take a *path* (``--parameters/-p``, ``--workdir/--wdir/-w``,
  ``--json-status``) get file/dir completion; everything else completes the flag
  list. ``-t/--server-threads`` suggests ``all`` plus a couple of common counts.
* The positional OPTION argument is ``key=value`` parameter syntax (and the
  integer N/p); we cannot meaningfully complete arbitrary keys, so we leave it to
  the default file/word behaviour and only complete the dashed options.
"""

import os
import sys

# Path-taking options get file completion in every shell.
FILE_OPTS = {"--parameters", "-p", "--workdir", "--wdir", "-w", "--json-status"}
# -t/--server-threads: a small curated value list ("all" + typical counts).
THREADS_OPTS = {"--server-threads", "-t"}
THREADS_VALUES = ["all", "1", "2", "4", "8", "16"]

HEADER = (
    "# cado-nfs.py {shell} completion -- GENERATED by scripts/build-completions.py\n"
    "# from cadofactor/toplevel.py. Do NOT hand-edit; regenerate instead:\n"
    "#   PYTHONPATH=scripts cado-nfs.venv/bin/python3 scripts/build-completions.py\n"
)


def collect_actions():
    """Return (all_option_strings, takes_value_map, help_map) from the parser."""
    sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
    from cadofactor import toplevel  # noqa: E402

    parser = toplevel.Cado_NFS_toplevel.default_parser()
    options = []
    takes_value = {}
    help_map = {}
    for action in parser._actions:
        if not action.option_strings:
            continue  # positional (the OPTION key=value catch-all)
        # nargs == 0 (store_true/store_const/help) => pure flag.
        is_flag = action.nargs == 0 or action.const is not None or \
            action.__class__.__name__ in ("_StoreTrueAction", "_StoreConstAction",
                                           "_HelpAction")
        for opt in action.option_strings:
            options.append(opt)
            takes_value[opt] = not is_flag
            help_map[opt] = (action.help or "").replace("\n", " ").strip()
    # Deterministic order for reproducible output.
    options = sorted(set(options))
    return options, takes_value, help_map


def gen_bash(options, takes_value, help_map):
    long_opts = " ".join(o for o in options if o.startswith("--"))
    short_and_long = " ".join(options)
    file_opts = " ".join(sorted(FILE_OPTS))
    thr_opts = " ".join(sorted(THREADS_OPTS))
    thr_vals = " ".join(THREADS_VALUES)
    out = HEADER.format(shell="bash")
    out += f"""
_cado_nfs_py()
{{
    local cur prev opts
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    opts="{short_and_long}"

    case "$prev" in
        {file_opts.replace(' ', '|')})
            COMPREPLY=( $(compgen -f -- "$cur") )
            return 0 ;;
        {thr_opts.replace(' ', '|')})
            COMPREPLY=( $(compgen -W "{thr_vals}" -- "$cur") )
            return 0 ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return 0
    fi
    # Otherwise the user is typing N or a key=value option; offer files too.
    COMPREPLY=( $(compgen -W "{long_opts}" -f -- "$cur") )
    return 0
}}
complete -F _cado_nfs_py cado-nfs.py
complete -F _cado_nfs_py ./cado-nfs.py
"""
    return out


def gen_zsh(options, takes_value, help_map):
    lines = [HEADER.format(shell="zsh"), "#compdef cado-nfs.py", "",
             "_cado_nfs_py() {", "  _arguments -s \\"]
    for opt in options:
        if opt in ("-h", "--help"):
            continue
        desc = help_map.get(opt, "").replace("'", "").replace("[", "(") \
            .replace("]", ")")
        desc = desc[:70]
        if opt in FILE_OPTS:
            lines.append(f"    '{opt}=[{desc}]:file:_files' \\")
        elif opt in THREADS_OPTS:
            vals = " ".join(THREADS_VALUES)
            lines.append(f"    '{opt}=[{desc}]:threads:({vals})' \\")
        elif takes_value.get(opt):
            lines.append(f"    '{opt}=[{desc}]:value:' \\")
        else:
            lines.append(f"    '{opt}[{desc}]' \\")
    lines.append("    '*:option (N or key=value):_files'")
    lines.append("}")
    lines.append("_cado_nfs_py \"$@\"")
    lines.append("")
    return "\n".join(lines)


def gen_fish(options, takes_value, help_map):
    out = [HEADER.format(shell="fish"),
           "# fish: source this file or drop it in ~/.config/fish/completions/",
           "function __cado_nfs_needs_value; end", ""]
    for opt in options:
        if not opt.startswith("--"):
            continue  # fish completions key on the long option; shorts via -s
        name = opt[2:]
        short = ""
        # Pair common short aliases.
        shorts = {"--parameters": "p", "--workdir": "w", "--server-threads": "t",
                  "--slaves": "s", "--help": "h"}
        if opt in shorts:
            short = f" -s {shorts[opt]}"
        desc = help_map.get(opt, "").replace("'", "")[:70]
        spec = f"complete -c cado-nfs.py -f -l {name}{short} -d '{desc}'"
        if opt in FILE_OPTS:
            spec = f"complete -c cado-nfs.py -F -l {name}{short} -d '{desc}'"
        elif opt in THREADS_OPTS:
            vals = " ".join(THREADS_VALUES)
            spec = (f"complete -c cado-nfs.py -x -l {name}{short} "
                    f"-a '{vals}' -d '{desc}'")
        out.append(spec)
    out.append("")
    return "\n".join(out)


def main():
    options, takes_value, help_map = collect_actions()
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    outdir = os.path.join(here, "misc", "completions")
    os.makedirs(outdir, exist_ok=True)
    artifacts = {
        "cado-nfs.bash": gen_bash(options, takes_value, help_map),
        "cado-nfs.zsh": gen_zsh(options, takes_value, help_map),
        "cado-nfs.fish": gen_fish(options, takes_value, help_map),
    }
    for name, content in artifacts.items():
        path = os.path.join(outdir, name)
        with open(path, "w") as f:
            f.write(content)
        print(f"wrote {os.path.relpath(path, here)} ({len(content)} bytes)")
    print(f"completions cover {len(options)} option strings")


if __name__ == "__main__":
    main()
